In [4]:
import numpy as np

In [5]:
# array for range

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# if we want our range in interval 

In [8]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [10]:
np.arange(0,50,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [11]:
np.arange(0,50,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [12]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
# array of 0,1 number

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
# linspace- space between the elements

In [18]:
np.linspace(0,10,2)

array([ 0., 10.])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
# eye-rows and column are same and will get one diagonally and zeros at the rest

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
# random number

In [26]:
np.random.rand(5)

array([0.17834137, 0.31892649, 0.25671114, 0.17501076, 0.46025113])

In [27]:
np.random.rand(3,4)

array([[0.88460707, 0.87627143, 0.71934216, 0.62474169],
       [0.56408879, 0.82898204, 0.73747521, 0.32025321],
       [0.95386999, 0.75058001, 0.51461314, 0.17764409]])

In [28]:
# random integer

In [29]:
np.random.randint(0,50)

10

In [30]:
np.random.randint(0,50,10)

array([ 6,  1,  6,  3, 41, 17, 38, 18, 30, 32])

In [31]:
# storing array

In [32]:
arr1= (np.random.randint(0,50,12))

In [33]:
arr1

array([30, 12, 26, 24, 49, 27, 30, 26,  2, 49, 29, 43])

In [34]:
arr1.shape

(12,)

In [35]:
# reshape

In [36]:
arr1.reshape(6,2)

array([[30, 12],
       [26, 24],
       [49, 27],
       [30, 26],
       [ 2, 49],
       [29, 43]])

In [37]:
arr1.reshape(2,6)

array([[30, 12, 26, 24, 49, 27],
       [30, 26,  2, 49, 29, 43]])

In [38]:
arr1.reshape(4,3)

array([[30, 12, 26],
       [24, 49, 27],
       [30, 26,  2],
       [49, 29, 43]])

In [39]:
arr1.reshape(3,4)

array([[30, 12, 26, 24],
       [49, 27, 30, 26],
       [ 2, 49, 29, 43]])

In [40]:
arr1.reshape(12,1)

array([[30],
       [12],
       [26],
       [24],
       [49],
       [27],
       [30],
       [26],
       [ 2],
       [49],
       [29],
       [43]])

In [41]:
# get lowest and highest element

In [43]:
arr1

array([30, 12, 26, 24, 49, 27, 30, 26,  2, 49, 29, 43])

In [42]:
arr1.min()

2

In [44]:
arr1.max()

49

In [45]:
# get index number of lowest and highest element

In [46]:
arr1.argmax()

4

In [47]:
arr1.argmin()

8

In [57]:
#get type

In [58]:
abc= (np.random.rand(10))

In [59]:
abc

array([0.27353346, 0.67055203, 0.9570729 , 0.78730773, 0.10506712,
       0.71763895, 0.87520264, 0.83223624, 0.48740307, 0.97498847])

In [64]:
abc1= (np.random.randint(0,100,10))

In [65]:
abc1

array([31, 73,  0, 39, 89, 97, 31, 91, 43, 50])

In [66]:
abc.dtype

dtype('float64')

In [67]:
abc1.dtype

dtype('int32')

In [71]:
text= np.array([1,4,9,16,25])

In [72]:
text

array([ 1,  4,  9, 16, 25])

In [73]:
np.sqrt(text) #(for square root) 

array([1., 2., 3., 4., 5.])

In [75]:
np.exp(text) #(for exponential) 

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

In [76]:
np.log(text) #(for logarithm) 

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582])

In [77]:
np.sin(text) #(for sin) 

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175])

In [78]:
np.cos(text) #(for cos)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281])

In [79]:
np.sum(text) #(for addition of all element)

55

In [81]:
np.mean(text) #(to calculate mean)

11.0

In [82]:
np.var(text) #(to calculate variance)

74.8

In [83]:
np.sqrt(np.var(text)) #(to calculate standard deviation)

8.648699324175862